// const allCategories = document.querySelectorAll(".item");
// console.log(`В списке ${allCategories.length} категории`);
// const animalList = allCategories[0].querySelectorAll("li");
// const animalTitle = allCategories[0].querySelector("h2");
// console.log(`Категория: ${animalTitle.textContent} `);
// console.log(`Количество элементов: ${animalList.length}`);
// const foodList = allCategories[1].querySelectorAll("li");
// const foodTitle = allCategories[1].querySelector("h2");
// console.log(`Категория: ${foodTitle.textContent} `);
// console.log(`Количество элементов: ${foodList.length}`);
// const techList = allCategories[2].querySelectorAll("li");
// const techTitle = allCategories[2].querySelector("h2");
// console.log(`Категория: ${techTitle.textContent} `);
// console.log(`Количество элементов: ${techList.length}`);

const allCategories = document.querySelectorAll(".item");
console.log(`В списке ${allCategories.length} категории`);
const animalTitle = allCategories[0].firstElementChild;
const animalList = allCategories[0].lastElementChild;
console.log(`Категория: ${animalTitle.textContent} `);
console.log(`Количество элементов: ${animalList.childElementCount}`);
const foodTitle = allCategories[1].firstElementChild;
const foodList = allCategories[1].lastElementChild;
console.log(`Категория: ${foodTitle.textContent} `);
console.log(`Количество элементов: ${foodList.childElementCount}`);
const techList = allCategories[2].lastElementChild;
const techTitle = allCategories[2].firstElementChild;
console.log(`Категория: ${techTitle.textContent} `);
console.log(`Количество элементов: ${techList.childElementCount}`);
